version: '3'
services:
  server:
    restart: unless-stopped
    container_name: dpc-nginx
    image: nginx:stable-alpine
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    networks:
      default:

  php:
    restart: unless-stopped
    container_name: dpc-fpm
    build: ./.docker/php/fpm
    working_dir: /app
    volumes:
      - ./.docker/php/composer-cache:/root/.composer/
      - ./:/app
    networks:
      default:

networks:
  default: